### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Boffice** [rsavordelli/s3bro#6]
Hello,
I am getting bellow errors:
` File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    result = (True, func(*args, **kwds))
    return map(*args)
    result = (True, func(*args, **kwds))
    return map(*args)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
  File "/usr/local/lib/python2.7/dist-packages/s3bro/ratelimit.py", line 25, in rate_limited_function
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
Process PoolWorker-8:
  File "/usr/local/lib/python2.7/dist-packages/s3bro/ratelimit.py", line 25, in rate_limited_function
    return map(*args)
Process PoolWorker-6:
    time.sleep( left_to_wait )
Process PoolWorker-9:
    return map(*args)
Traceback (most recent call last):
    time.sleep( left_to_wait )
  File "/usr/local/lib/python2.7/dist-packages/s3bro/ratelimit.py", line 29, in rate_limited_function
Traceback (most recent call last):
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s3bro/ratelimit.py", line 29, in rate_limited_function
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
KeyboardInterrupt
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    ret = func( *args, **kwargs )
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    ret = func( *args, **kwargs )
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/s3bro/s3_restore.py", line 100, in restore_default
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/s3bro/s3_restore.py", line 100, in restore_default
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    if obj.storage_class == 'GLACIER':
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    if obj.storage_class == 'GLACIER':
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 339, in property_loader
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 339, in property_loader
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 113, in worker
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 113, in worker
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    self.load()`

**Comment by rsavordelli** [comment]
Hey.

Please share the steps to reproduce.

1. command you run (omit your bucket and key names)
2. python version
3. OS version

**Comment by Boffice** [comment]
Hello,

1) s3bro restore --bucket "bucketname" --days 20 --type Bulk
2) python2.7
3) WSL Ubuntu 20
